import "@/styles/global.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry'
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/*<React.StrictMode>*/}
          <AntdRegistry>
            {children}
          </AntdRegistry>
        {/*</React.StrictMode>*/}
      </body>
    </html>
  );
}
